### ISSUE TITLE
invalid URL on narfiles

### ISSUE THREAD

**Issue by magnetophon** [edolstra/nix-serve#3]
When I nixos-rebuild, I get 
```*** Downloading `2.2.2.2:5000/nar/$hash.nar.bz2` (signed by 'mixos') to $path```
followed by  ``invalid URL  `2.2.2.2:5000/nar/$hash.nar.bz2` `` .
When I manually wget that URL, it's fine. 
The rebuilds get an entry in the journal for sshd.service and nix-daemon.service, but nix-serve only get's an entry when I restart the service. 
Not even ``journalctl -o verbose -u nix-serve.service`` shows anything.

The relevant parts of the server and client configs are [here](https://github.com/magnetophon/nixosConfig/blob/master/machines/mixos/default.nix#L21) and [here](https://github.com/magnetophon/nixosConfig/blob/master/machines/compnix/machine.nix#L98).

**Comment by edolstra** [comment]
The binary cache URL should be a proper URL, i.e. `http://2.2.2.2:5000/`, not `2.2.2.2:5000`.

**Comment by magnetophon** [comment]
That was it. 
Dank je wel!
