### ISSUE TITLE
kindly warn on bad values in NIX_SECRET_KEY_FILE

### ISSUE THREAD

**Issue by asdf8dfafjk** [edolstra/nix-serve#40]
I have given it a non-existant file, and a file with bad values and I get no warning.

**Comment by jfeser** [comment]
+1. I just ran into #10, and it would really help if nix-serve exited with an error when you fail to pass a key. Also, the readme doesn't make it clear that providing a secret key is not optional.

**Comment by asdf8dfafjk** [comment]
Hey @jfeser I can't get nix-serve to work at all no matter what. Which guide did you try to get it work for you if you did?

**Comment by jfeser** [comment]
I followed the readme. What errors are you seeing?

**Comment by asdf8dfafjk** [comment]
@jfeser The readme of this repo? So the sense I got from the readme was that signing was optional. That said, I did try both unsigned first and then signed version later but I just could not get substitution to work. I'm going to try again next time and post errors here.
