### ISSUE TITLE
Compression is not configurable

### ISSUE THREAD

**Issue by steveeJ** [edolstra/nix-serve#5]
It'd be useful to make the compression for nars configurable. At this point _bzip2_ is hardcoded, but I know that _xz_ is also supported. Additionally it would be great to allow for no compression, but I'm not sure if narinfo supports that.

**Comment by ip1981** [comment]
FYI https://github.com/zalora/nixsap/blob/c8fe05f1c72412c2f1fd5f1adc9989eab4fc0d50/modules/pkgs/nix-serve/nix-serve.psgi

**Comment by edolstra** [comment]
Closing since `nix-serve` no longer compresses NARs.
